tasks:
  - init: npm install && npm run watch
  - command: mkdir dist && cd dist && python3 -m http.server 8080
    name: Static Server
  
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
